version: "3"

services:
  tmail-backend:
    image: linagora/tmail-backend:memory-branch-master
    container_name: tmail-backend
    volumes:
      - ./jwt_publickey:/root/conf/jwt_publickey
      - ./jwt_privatekey:/root/conf/jwt_privatekey
      - ./mailetcontainer.xml:/root/conf/mailetcontainer.xml
      - ./imapserver.xml:/root/conf/imapserver.xml
      - ./jmap.properties:/root/conf/jmap.properties
    ports:
      - "80:80"
    environment:
      - DOMAIN=example.com
    networks:
      - tmail

networks:
  tmail:
