on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"

name: Build Docker images

jobs:
  build-dev-image:
    name: Build development image
    if: github.ref_type == 'branch' && github.ref_name == 'master'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          cache-from: |
            type=gha
          cache-to: |
            type=gha
          tags: |
            ghcr.io/tk-nguyen/tmail-web:${{ github.ref_name }}

  build-release-image:
    name: Build release image
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          cache-from: |
            type=gha
          cache-to: |
            type=gha
          tags: |
            ghcr.io/tk-nguyen/tmail-web:${{ github.ref_name }}
