name: Integration tests

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  FLUTTER_VERSION: 3.22.2

jobs:
  mobile_integration_test:
    permissions:
      contents: "read"
      id-token: "write"

    name: Run integration tests for mobile apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Test
        run: gcloud firebase test android models list
