name: Integration tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**/*.md"

env:
  JAVA_VERSION: 22

jobs:
  integration_test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven
          cache-dependency-path: "tmail_selenium/pom.xml"

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - uses: browser-actions/setup-firefox@v1
      - uses: browser-actions/setup-geckodriver@latest

      - name: Configure frontend
        env:
          FRONTEND_CONFIG: ${{ secrets.FRONTEND_CONFIG }}
        run: |
          echo "$FRONTEND_CONFIG" > env.file
        working-directory: tmail_selenium

      - name: Run integration tests
        run: ../scripts/integration-tests.sh
        working-directory: tmail_selenium
